server:
  port: 8181 #端口号
  shutdown: graceful #开启优雅停机 默认为immediate立即停机

spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 8x#L9q$vN2!pK@mW
      timeout: 10000

logging:
  config: classpath:log4j2.xml


